//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ESocietyEntities : DbContext
    {
        public ESocietyEntities()
            : base("name=ESocietyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<House> Houses { get; set; }
        public DbSet<Login> Logins { get; set; }
        public DbSet<Resident> Residents { get; set; }
        public DbSet<ServiceProvider> ServiceProviders { get; set; }
        public DbSet<Society> Societies { get; set; }
    }
}
