//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Society
    {
        public Society()
        {
            this.Houses = new HashSet<House>();
            this.ServiceProviders = new HashSet<ServiceProvider>();
        }
    
        public int societyid { get; set; }
        public string societyname { get; set; }
        public string area { get; set; }
    
        public virtual ICollection<House> Houses { get; set; }
        public virtual ICollection<ServiceProvider> ServiceProviders { get; set; }
    }
}
